version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: kioga-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
