version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: kioga_db
      MYSQL_USER: kioga_user
      MYSQL_PASSWORD: kioga_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
    container_name: kioga-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
